config/routes.rb
Rails.application.routes.draw do
  devise_for :users

    root 'pages#index'
    match 'welcome' => 'pages#welcome', :via => :get
    match 'contact_us' => 'pages#contactus', :via => :get
    match 'about_us' => 'pages#aboutus', :via => :get
    match 'how_it_work' => 'pages#howitwork', :via => :get
    match 'be_an_employer' => 'pages#beanemployer', :via => :get
    match 'be_a_freelancer' => 'pages#beafreelancer', :via => :get
    match 'register_employer' => 'users#register_employer', :via => :get
    match 'register_freelancer' => 'users#register_freelancer', :via => :get
    match 'save_employer' => 'users#save_employer', :via => :post
    match 'save_freelancer' => 'users#save_freelancer', :via => :post
    match 'get_position' => 'users#get_position', :via => :get
    match 'freelancer/:name' => 'freelancers#view_profile', :via => :get
    match 'employer/:name' => 'employers#view_profile', :via => :get

    resources :users do
      collection do
        post 'register'
      end

      member do
        put 'update_password'
        get 'change_password'

      end
    end

    resources :projects do
      member do
        post 'post_bid'
        get 'detail'
        put 'assign_consultant'
      end
    end
    resources :contact_us
    resources :freelancers
    resources :employers

    namespace :admin do
      resources :freelancers
      resources :employers
      resources :projects do
        member do
          put 'assign_consultant'
        end
      end
      resources :internal_users do
        collection do 
          get 'my_profile'
          put 'update_password'
          get 'change_password'
        end
      end
    end

end

app/views/pages/aboutus.html.erb
<div class="container">
	<legend class="text-left">About US</legend>
	<p>
		SabayTrade is an online freelancing community. We are working inspire young Cambodians to be independent by using their skills to earn their living and, most importantly, to build their confidence in business or working world. 
	</p>
	<p>
		We encourage young professionals around the country to trade their professional skills for money rather than asking for money.
	</p>
	<b> How It Works </b><br />
	It is very simple
  <div class="row" style="margin: 10px 0px;">
    <div class="col-lg-6">
    	<legend class="text-left" style="font-size:15px;">Employers</legend>
    	<ol>
    		<li>Employers have projects to be done.</li>
    		<li>Employers register in SabayTrade.</li>
    		<li>Employers post the projects in SabayTrade.</li>
    		<li>SabayTrade will contact to confirm.</li>
    		<li>Projects display in SabayTrade.</li>
    	</ol>
    </div>
    <div class="col-lg-6">
    	<legend class="text-left" style="font-size:15px;">Freelancers</legend>
    	<ol>
    		<li>Freelancers want projects to do.</li>
    		<li>Freelancers register in SabayTrade.</li>
    		<li>Freelancers bid the project that they can do.</li>
    		<li>Freelancers will be contacted if they get the project.</li>
    		<li>Freelancers do the work; Employers pay the money.</li>
    	</ol>
    </div>
  </div>
</div>

app/views/pages/contactus.html.erb
<div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <%= form_for(@contact_us, :url => {:action => "create", :controller => 'contact_us'} , :html => {:class => 'form-horizontal'} ) do |f| %>    
          <fieldset>
            <legend class="text-left">Contact and Supports</legend>
    
            <!-- Name input-->
            <div class="form-group">
              <label class="col-md-3 control-label" for="name">First Name</label>
              <div class="col-md-9">
                <%= f.text_field :first_name, :class =>"form-control", :required => "required", :placeholder => "Your first name" %>
              </div>
            </div>

            <!-- Name input-->
            <div class="form-group">
              <label class="col-md-3 control-label" for="name">Last Name</label>
              <div class="col-md-9">
                <%= f.text_field :last_name, :class =>"form-control", :required => "required", :placeholder => "Your last name" %>
              </div>
            </div>
    
            <!-- Email input-->
            <div class="form-group">
              <label class="col-md-3 control-label" for="email">Your E-mail</label>
              <div class="col-md-9">
                <%= f.text_field :email, :class =>"form-control", :required => "required", :placeholder => "Your email" %>
              </div>
            </div>

            <!-- Subject input-->
            <div class="form-group">
              <label class="col-md-3 control-label" for="name">Subject</label>
              <div class="col-md-9">
                <%= f.text_field :subject, :class =>"form-control", :required => "required", :placeholder => "Your subject" %>
              </div>
            </div>
    
            <!-- Message body -->
            <div class="form-group">
              <label class="col-md-3 control-label" for="message">Your message</label>
              <div class="col-md-9">
                <%= f.text_area :description, :class =>"form-control", :required => "required", :placeholder => "Please enter your message here...", :row => "5" %>
              </div>
            </div>

            <!-- Form actions -->
            <div class="form-group">
              <div class="col-md-12 text-right">
                <button class="btn btn-primary">Send</button>
              </div>
            </div>
          </fieldset>
        <% end %>
      </div>
    </div>
</div>

app/views/pages/howitwork.html.erb
<div class="text-center">
  <div class="subtitle" style="margin-top:30px;">
    How it works. 
  </div>
  <br />
  <div class="vid">
    <iframe width="560" height="315" src="//www.youtube.com/embed/ac7KhViaVqc" allowfullscreen=""></iframe>
  </div>
  <br />
  <%= link_to "Be an employer", be_an_employer_path(), :method => :get, :class => "btn btn-success btn-lg longbutton" %>
  <%= link_to "Be a freelancer", be_a_freelancer_path(), :method => :get, :class => "btn btn-success btn-lg longbutton" %>
  <br />
  <br />
</div>
<div class="clear"></div>

app/views/pages/welcome.html.erb
<center>
  <div class="row">
    <div class="col-lg-4">
      <img src="/developer.jpg" alt="..." class="img-rounded dashboard">
      <center>
        <a href="<%= register_freelancer_path() %>" class="btn btn-info">Freelancers</a>
      </center>
    </div>

    <div class="col-lg-4">
      <img src="/project.jpg" alt="..." class="img-rounded dashboard">
      <center>
        <a href="<%= projects_path() %>" class="btn btn-info">Projects</a>
      </center>
    </div>

    <div class="col-lg-4">
      <img src="/employer.jpg" alt="..." class="img-rounded dashboard">
      <center>
        <a href="<%= register_employer_path() %>" class="btn btn-info">Employers</a>
      </center>
    </div>
  </div>
  <h5>Get Your Work Done With the Right People and Price.</h5>
</center>