config/routes.rb
Rails.application.routes.draw do
  devise_for :users

    root 'pages#index'
    match 'welcome' => 'pages#welcome', :via => :get
    match 'contact_us' => 'pages#contactus', :via => :get
    match 'about_us' => 'pages#aboutus', :via => :get
    match 'how_it_work' => 'pages#howitwork', :via => :get
    match 'be_an_employer' => 'pages#beanemployer', :via => :get
    match 'be_a_freelancer' => 'pages#beafreelancer', :via => :get
    match 'register_employer' => 'users#register_employer', :via => :get
    match 'register_freelancer' => 'users#register_freelancer', :via => :get
    match 'save_employer' => 'users#save_employer', :via => :post
    match 'save_freelancer' => 'users#save_freelancer', :via => :post
    match 'get_position' => 'users#get_position', :via => :get
    match 'freelancer/:name' => 'freelancers#view_profile', :via => :get
    match 'employer/:name' => 'employers#view_profile', :via => :get

    resources :users do
      collection do
        post 'register'
      end

      member do
        put 'update_password'
        get 'change_password'

      end
    end

    resources :projects do
      member do
        post 'post_bid'
        get 'detail'
        put 'assign_consultant'
      end
    end
    resources :contact_us
    resources :freelancers
    resources :employers

    namespace :admin do
      resources :freelancers
      resources :employers
      resources :projects do
        member do
          put 'assign_consultant'
        end
      end
      resources :internal_users do
        collection do 
          get 'my_profile'
          put 'update_password'
          get 'change_password'
        end
      end
    end

end

app/models/project.rb
class Project < ActiveRecord::Base
	validates_presence_of :name, :description, :budget, :end_date, :start_date, :industry, :sub_industry, :status
	attr_accessible :name, :status, :industry, :sub_industry,  :description, :budget, :end_date, :start_date, :consultant_id, :consultant_cost, :tags

	belongs_to :user
	has_many :bid_projects, dependent: :destroy

	STATUS = {
    "Bidding" => "Bidding",
    "On going" => "On going",
    "Dalayed" => "Dalayed",
    "Finished" => "Finished"
  }

	def consultant
		User.find_by_id(self.consultant_id)
	end

	def consultant_name
		user = User.find_by_id(self.consultant_id)
		return user.display_name if user 
    ""
	end

	def employer_name
		return self.user.display_name if self.user 
    ""
	end

	def lowest_bid
		lowest = self.budget
		self.bid_projects.each do |bp|
			if bp.cost and lowest.to_i > bp.cost.to_i
				lowest = bp.cost.to_i
			end
		end
		return lowest
	end

	def bid_by_user user
		return false unless user
		self.bid_projects.each do |bp|
			return true if bp.user_id == user.id
		end
		false
	end

end

app/models/project_type.rb
class ProjectType < ActiveRecord::Base
  attr_accessible :name
  has_many :projects
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :validate_user

	def index
    @projects = Project.all
    render layout: "admin"
  end

  def new
    @project = Project.new
  end

  def edit
    @project = Project.find_by_id params[:id]
    @bid_projects = @project.bid_projects
    render layout: "admin"
  end

  def show
    @project = Project.find_by_id params[:id]
    render layout: "admin"
  end

  def update
    @project = Project.find_by_id params[:id]
    if @project.update_attributes!(params[:project])
      redirect_to admin_project_path(@project)
    else
      render :edit
    end
  end

  def destroy
    @project = Project.find_by_id params[:id]
    if @project.destroy!
      redirect_to admin_projects_path()
    else
      flash[:error] = "Failed to delete project."
      redirect_to admin_projects_path()
    end
  end

  def create
    if params[:project]["end_date"]
      end_date = DateTime.strptime(params[:project]["end_date"], "%m-%d-%Y").to_date.to_s 
      params["project"].delete("end_date")
    else
      end_date = params[:project]["end_date"]
    end
    @project = current_user.projects.new(params[:project])
    @project.end_date = end_date
    @project.start_date = DateTime.now();
    @project.save!
  end

  def assign_consultant
    @project = Project.find_by_id params[:id]
    if @project.update_attributes!(params[:project])
      redirect_to admin_project_path(@project)
    else
      render :edit
    end
  end

  private

  def validate_user
    head :forbidden unless current_user.type.name == 'admin'
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index]
  before_filter :validate_user, :except => [:show, :index, :post_bid, :detail]

	def index
    @active_projects = Project.all
    @projects = Project.all.paginate(:page => params[:page], :per_page => 10)
  end

  def new
    @project = Project.new
  end

  def create
    if params[:project]["end_date"]
      end_date = DateTime.strptime(params[:project]["end_date"], "%m-%d-%Y").to_date.to_s 
      params["project"].delete("end_date")
    else
      end_date = params[:project]["end_date"]
    end
    @project = current_user.projects.new(params[:project])
    @project.end_date = end_date
    @project.start_date = DateTime.now();
    if @project.save!
      redirect_to employers_path
    end
  end

  def edit
    @project = current_user.projects.find_by_id params[:id]
    @bid_projects = @project.bid_projects
  end

  def show
    @project = Project.find_by_id params[:id]
  end

  def detail
    @project = Project.find_by_id params[:id]
  end

  def update
    @project = Project.find_by_id params[:id]
    if @project.update_attributes!(params[:project])
      redirect_to project_path(@project)
    else
      render :edit
    end
  end

  # def show
  #   @project = Project.find_by_id params[:id]
  #   @bid = BidProject.find_by_project_id_and_user_id(params[:id],current_user.id)
  #   unless @bid
  #     @bid = BidProject.new
  #   end
  # end

  def post_bid
    @project = Project.find_by_id params[:id]
    @bid = BidProject.find_by_project_id_and_user_id(params[:id],current_user.id)
    unless @bid
      if params["bid_project"]["cost"].to_i < @project.lowest_bid
        @bid = BidProject.create!(:project => @project, :user => current_user, :cost => params["bid_project"]["cost"])
        redirect_to project_path(@project)
      else
        @project.errors.add("Bid", " was not accepted.Please input your bid below $#{@project.lowest_bid}.")
        render :show
      end  
    else
      @project.errors.add("Project", "Could not find project to bid.")
      render :show
    end
  end

  def assign_consultant
    @project = current_user.projects.find_by_id params[:id]
    if @project.update_attributes!(params[:project])
      redirect_to project_path(@project)
    else
      render :edit
    end
  end

  private

  def validate_user
    head :forbidden unless (current_user.type.name == 'employer' || current_user.type.name == 'admin')
  end

end

app/views/projects/_assign_form.html.erb
<%= form_for(project, :url => {:action => action} , :method => :put, :html => {:class => 'form-horizontal'} ) do |f| %>       
  <fieldset>
    <legend class="text-left">Project Assignment</legend>
    <div class="form-group">
      <label class="col-md-3 control-label">Consultant</label>
      <div class="col-md-9">
        <%= f.select(:consultant_id, options_for_select(@bid_projects.collect {|p| [p.user.display_anonymous_name, p.user.id] }, f.object.consultant_id), {},{ :class => 'form-control' }) %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-md-3 control-label">Budget</label>
      <div class="col-md-9">
        <%= f.text_field :consultant_cost, :class =>"form-control", :required => "required", :placeholder => "Agreement project cost ($)" %>
      </div>
    </div>

    <!-- Form actions -->
    <div class="form-group">
      <label class="col-md-3 control-label" ></label>
      <div class="col-md-9">
        <button class="btn btn-success">Assign Project</button>
      </div>
    </div>
        
  </fieldset>
<% end %>

app/views/projects/_bid_form.html.erb
<%= form_for(project, :url => {:action => action} , :method => :post, :html => {:class => 'form-horizontal', :onsubmit => "return validateBid()"} ) do |f| %>    
  <% if @project.errors.any?%>
    <div class="alert alert-danger">
      <h4><%= pluralize(@project.errors.count, "error") %> prohibited this post from being bid:</h4>
      <ul>
        <% @project.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>   
  <fieldset>
    
    <div class="form-group">
      <label class="col-md-3 control-label">Your bid</label>
      <div class="col-md-9">
        <%= f.text_field :cost, :class =>"form-control", :required => "required", :placeholder => "Agreement project cost ($)" %>
      </div>
    </div>

    <input type="hidden" value='<%= lowest_bid %>' id="lowest_bid" >

    <!-- Form actions -->
    <div class="form-group">
      <label class="col-md-3 control-label" ></label>
      <div class="col-md-9">
        <button class="btn btn-success">Agree to bid</button>
      </div>
    </div>
  </fieldset>
<% end %>

<script>
  function validateBid(){
    if(parseInt($("#bid_project_cost").val()) > parseInt($("#lowest_bid").val())){
      alert("Your bid is not accepted. Latest bid is $" + $("#lowest_bid").val().toString());
      return false;
    }
    return true;
  }
</script>

app/views/projects/_form.html.erb
<%= form_for(project, :url => {:action => action} , :html => {:class => 'form-horizontal'} ) do |f| %>       
  <fieldset>
    <legend class="text-left">New Project</legend>
<!--     <div class="form-group">
      <label class="col-md-3 control-label" for="name">Project Type</label>
      <div class="col-md-9">
        <%= f.select(:project_type_id, options_for_select(ProjectType.all.collect {|p| [p.name,p.id] }, "Select type"), {},{ :class => 'form-control' }) %>
      </div>
    </div> -->

    <div class="form-group">
      <label class="col-md-3 control-label" for="name">Project Title</label>
      <div class="col-md-9">
        <%= f.text_field :name, :class =>"form-control", :required => "required", :placeholder => "Your project title" %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-md-3 control-label" for="name">Industry</label>
      <div class="col-md-9">
        <%= f.select(:industry, options_for_select(Industry::INDUSTRY.collect {|key,value| [key,value] }, f.object.industry), {},{ :class => 'form-control', :onchange => 'queryPosition(this)' }) %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-md-3 control-label" for="name">Sub Industry</label>
      <div class="col-md-9">
        <%= f.select(:sub_industry, options_for_select(Industry.selected_position(project.industry).collect {|key,value| [key,value] }, f.object.sub_industry), {},{ :class => 'form-control', :onchange => 'queryPosition(this)' }) %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-md-3 control-label" for="name">Description</label>
      <div class="col-md-9">
        <%= f.text_area :description, :class =>"form-control", :required => "required", :placeholder => "Please enter your project description here..." %>
      </div>
    </div>    

    <div class="form-group">
      <label class="col-md-3 control-label" for="name">Budget</label>
      <div class="col-md-9">
        <%= f.text_field :budget, :class =>"form-control", :required => "required", :placeholder => "Your project budget" %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-md-3 control-label" for="name">Deadline</label>
      <div class="col-md-9">
        <%= f.text_field :end_date, :class =>"form-control datepicker", :required => "required", :placeholder => "Your project deadline" %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-md-3 control-label" for="name">Tags</label>
      <div class="col-md-9">
        <%= f.text_field :tags, "data-role" => "tagsinput",  :class =>"form-control", :required => "required" %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-md-3 control-label" for="name">Status</label>
      <div class="col-md-9">
        <%= f.select(:status, options_for_select(Project::STATUS.collect {|key,value| [key,value] }, f.object.status), {},{ :class => 'form-control', :onchange => 'queryPosition(this)' }) %>
      </div>
    </div>


    <!-- Form actions -->
    <div class="form-group">
      <label class="col-md-3 control-label" ></label>
      <div class="col-md-9">
        <button class="btn btn-success">Post The Project</button>
      </div>
    </div>
        
  </fieldset>
<% end %>

<script>
    $('.datepicker').datepicker({format: 'mm-dd-yyyy'})
</script>

app/views/projects/_form_edit.html.erb
<%= form_for(project, :url => {:action => action} , :html => {:class => 'form-horizontal'} ) do |f| %>       
  <fieldset>

    <div class="form-group">
      <label class="col-md-3 control-label">Project Title</label>
      <div class="col-md-9">
        <%= f.text_field :name, :class =>"form-control", :required => "required", :placeholder => "Your project title" %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-md-3 control-label">Description</label>
      <div class="col-md-9">
        <%= f.text_area :description, :class =>"form-control tinymce", :required => "required", :placeholder => "Please enter your project description here..." %>
      </div>
    </div> 

    <div class="form-group">
      <label class="col-md-3 control-label" for="name">Industry</label>
      <div class="col-md-9">
        <%= f.select(:industry, options_for_select(Industry::INDUSTRY.collect {|key,value| [key,value] }, f.object.industry), {},{ :class => 'form-control', :onchange => 'queryPosition(this)' }) %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-md-3 control-label" for="name">Sub Industry</label>
      <div class="col-md-9">
        <%= f.select(:sub_industry, options_for_select(Industry.selected_position(project.industry).collect {|key,value| [key,value] }, f.object.sub_industry), {},{ :class => 'form-control', :onchange => 'queryPosition(this)' }) %>
      </div>
    </div>   

    <div class="form-group">
      <label class="col-md-3 control-label">Budget</label>
      <div class="col-md-9">
        <%= f.text_field :budget, :class =>"form-control", :required => "required", :placeholder => "Your project budget" %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-md-3 control-label" >Deadline</label>
      <div class="col-md-9">
        <%= f.text_field :end_date, :class =>"form-control datepicker", :required => "required", :placeholder => "Your project deadline" %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-md-3 control-label" >Tags</label>
      <div class="col-md-9">
        <%= f.text_field :tags, "data-role" => "tagsinput",  :class =>"form-control", :required => "required" %>
      </div>
    </div>


    <!-- Form actions -->
    <div class="form-group">
      <label class="col-md-3 control-label" ></label>
      <div class="col-md-9">
        <button class="btn btn-success">Update The Project</button><a href="<%= employers_path() %>" class="btn btn-danger">Cancel</a>
      </div>
    </div>
        
  </fieldset>
<% end %>

<script>
    $('.datepicker').datepicker({format: 'mm-dd-yyyy'})
</script>

app/views/projects/_form_show.html.erb
<form class='form-horizontal' >   
  <fieldset>
    <legend class="text-left"><%= project.name %><h5>Posted by <%= link_to project.user.display_name, employer_path(project.user), :method => :get %></h5></legend>

    <div class="form-group">
      <label class="col-md-3 control-label">Industry</label>
      <div class="col-md-9 top-seven">
        : <%= project.industry %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-md-3 control-label">Sub Industry</label>
      <div class="col-md-9 top-seven">
        : <%= project.sub_industry %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-md-3 control-label">Description</label>
      <div class="col-md-9 top-seven">
        : <%= project.description %>
      </div>
    </div>    

    <div class="form-group">
      <label class="col-md-3 control-label">Budget</label>
      <div class="col-md-9 top-seven">
       : $<%= project.budget %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-md-3 control-label" >Deadline</label>
      <div class="col-md-9 top-seven">
        : <%= project.end_date.to_date() %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-md-3 control-label" >Tags</label>
      <div class="col-md-9 top-seven">
        : <%= project.tags %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-md-3 control-label">Staus</label>
      <div class="col-md-9 top-seven">
        : <%= project.status %>
      </div>
    </div>

    <!-- Form actions -->
    <% if current_user and current_user.is_employee? %>
      <div class="form-group">
        <label class="col-md-3 control-label" ></label>
        <div class="col-md-9">
          <%= link_to "Edit Project", edit_project_path(project), :method => :get, :class => "btn btn-success" %>
          <%= link_to "Cancel", employers_path(), :method => :get, :class => "btn btn-danger" %>
        </div>
      </div>
    <% end %>
        
  </fieldset>
</form>

app/views/projects/detail.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-1">
    </div>
    <div class="col-lg-6">
      <%= render "form_show", {:project => @project} %>
    </div>
    <div class="col-lg-4">
      <legend class="text-left">Who bidding this project</legend>
        <% if @project.bid_projects.size > 0 %>
          <ul class="list-group">
            <% @project.bid_projects.each do |p| %>
              <%= link_to "#{p.user.display_anonymous_name}", "javascript:void(0)", :method => :get, :class => "list-group-item" %>
            <% end %>
          </ul>
          <% if @project.bid_by_user current_user%>
            You already bid this project with the cost of $<%= @project.bid_projects.where("user_id = ?", current_user.id).first.cost %>
          <% else %>
            <% if current_user.type.name == "freelancer" %>
              <legend class="text-left">Bid this project</legend>
              <%= render "bid_form", {:project => @project.bid_projects.new(:user => current_user || nil), :action => "post_bid" } %>
            <% else %>
              
            <% end %>
          <% end %>
          <% if @project.consultant %>
            <legend class="text-left">Project Assignment</legend>
            This project is successfully assigned to <%= link_to @project.consultant.display_name, admin_freelancer_path(@project.consultant), :method => :get %>
          <% end %>
        <% else %>
          No bidding yet <br /><br />
          <legend class="text-left">Bid this project</legend>
          <%= render "bid_form", {:project => @project.bid_projects.new(:user => current_user || nil), :action => "post_bid" } %>
        <% end %>
    </div>
  </div>
</div>

app/views/projects/edit.html.erb
<div class="container">
  <div class="row">
  	<div class="col-lg-1">
    </div>
    <div class="col-lg-6">
      <%= render "form_edit", {:project => @project, :action => "update" } %>
    </div>
    <div class="col-lg-4">
    	<legend class="text-left">Who bid this project</legend>
    		<% if @project.bid_projects.size > 0 %>
	        <ul class="list-group">
	          <% @project.bid_projects.each do |p| %>
	            <%= link_to "#{p.user.display_anonymous_name} - $#{p.cost}", "javascript:void(0)", :method => :get, :class => "list-group-item" %>
	          <% end %>
	        </ul>
          <% if @project.consultant %>
            <legend class="text-left">Project Assignment</legend>
            This project is successfully assigned to <%= link_to @project.consultant.display_name, freelancer_path(@project.consultant), :method => :get %>
          <% else %>
            <%= render "assign_form", {:project => @project, :action => "assign_consultant" } %>
          <% end %>
	      <% else %>
	      	No bidding yet
	      <% end %>
    </div>
  </div>
</div>

app/views/projects/index.html.erb
<div class="container dynamicTile">
  <center>
    <p>
      <h3> Most Visited Projects </h3>
    </p>
  </center>
  <div class="row ">
    <% @active_projects.each do |p| %>     
      <div class="col-sm-2 col-xs-4 well" style="margin:5px;">
      	<div id="tile1" class="tile">
           <div class="carousel slide" data-ride="carousel">
            <!-- Wrapper for slides -->
            <div class="carousel-inner">
              <div class="item active">
                  <h4> <%= link_to p.name, project_path(p), :method => :get %> </h4>
                  <h5> <%= p.tags %></h5>
                  <h5> $<%= p.budget %></h5>
              </div>
              
            </div>
          </div>
      	</div>
    	</div>
    <% end %>
  </div>
  <center>
    <p>
      <h3> All Active Projects </h3>
    </p>
  </center>
  <table id="mytable" class="table table-border table-striped">
    <thead>
      <th>Project</th>
      <th>Category</th>
      <th>Relevant Skill</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Budget</th>
    </thead>
    <% @projects.each do |p| %>     
      <tbody>
        <tr>
          <td><%= link_to p.name, project_path(p), :method => :get %></td>
          <td><%= p.industry %></td>
          <td><%= p.tags %></td>
          <td><%= p.start_date.to_date %></td>
          <td><%= p.end_date.to_date %></td>
          <td>$<%= p.budget %></td>
        </tr>
      </tbody>
    <% end %>
  </table>
  <%= will_paginate @projects, :param_name => 'page', renderer: BootstrapPagination::Rails %>
</div>

app/views/projects/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= render "form", {:project => @project, :action => "create" } %>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-1">
    </div>
    <div class="col-lg-6">
      <%= render "form_show", {:project => @project} %>
    </div>
    <div class="col-lg-4">
      <legend class="text-left">Who bid this project</legend>
      <% if @project.bid_projects.size > 0 %>
        <ul class="list-group">
          <% @project.bid_projects.each do |p| %>
            <%= link_to "#{p.user.display_anonymous_name} - $#{p.cost}", freelancer_path(p.user), :method => :get, :class => "list-group-item" %>
          <% end %>
        </ul>
      <% else %>
        No bidding yet <br /><br />
      <% end %>
      <% if @project.consultant %>
        <legend class="text-left">Project Assignment</legend>
        This project is successfully assigned to <%= link_to @project.consultant.display_anonymous_name, freelancer_path(@project.consultant), :method => :get %>
      <% else %>
        <% if current_user %>
          <% unless @project.bid_by_user current_user %>
            <% if current_user.type.name != "employer" %>
              <legend class="text-left">Bid this project</legend>
              <%= render "bid_form", {:project => @project.bid_projects.new(:user => current_user || nil), :action => "post_bid", :lowest_bid => @project.lowest_bid } %>
            <% end %>
          <% else %>
            You already bid this project with the cost of $<%= @project.bid_projects.where("user_id = ?", current_user.id).first.cost %>
          <% end %>
        <% else %>
           <a href="<%= detail_project_path(@project) %>" class="btn btn-danger">Sign in to bid</a>
        <% end %>
      <% end %>
    </div>
  </div>
</div>