config/routes.rb
Rails.application.routes.draw do
  devise_for :users

    root 'pages#index'
    match 'welcome' => 'pages#welcome', :via => :get
    match 'contact_us' => 'pages#contactus', :via => :get
    match 'about_us' => 'pages#aboutus', :via => :get
    match 'how_it_work' => 'pages#howitwork', :via => :get
    match 'be_an_employer' => 'pages#beanemployer', :via => :get
    match 'be_a_freelancer' => 'pages#beafreelancer', :via => :get
    match 'register_employer' => 'users#register_employer', :via => :get
    match 'register_freelancer' => 'users#register_freelancer', :via => :get
    match 'save_employer' => 'users#save_employer', :via => :post
    match 'save_freelancer' => 'users#save_freelancer', :via => :post
    match 'get_position' => 'users#get_position', :via => :get
    match 'freelancer/:name' => 'freelancers#view_profile', :via => :get
    match 'employer/:name' => 'employers#view_profile', :via => :get

    resources :users do
      collection do
        post 'register'
      end

      member do
        put 'update_password'
        get 'change_password'

      end
    end

    resources :projects do
      member do
        post 'post_bid'
        get 'detail'
        put 'assign_consultant'
      end
    end
    resources :contact_us
    resources :freelancers
    resources :employers

    namespace :admin do
      resources :freelancers
      resources :employers
      resources :projects do
        member do
          put 'assign_consultant'
        end
      end
      resources :internal_users do
        collection do 
          get 'my_profile'
          put 'update_password'
          get 'change_password'
        end
      end
    end

end

app/controllers/admin/employers_controller.rb
class Admin::EmployersController < ApplicationController
	before_filter :authenticate_user!
  before_filter :validate_user

  def index
    @user = User.where('type_id = ?', 2)
    render layout: "admin"
  end

  def show
    @profile = User.find_by_id(params[:id]).profile
    @profile.dob = @profile.dob.strftime("%d-%m-%Y") if @profile.dob
    render layout: "admin"
  end

  def edit
    @profile = User.find_by_id(params[:id]).profile
    unless @profile.dob
      @profile.dob = DateTime.now().strftime("%d-%m-%Y")
    else
      @profile.dob = @profile.dob.strftime("%d-%m-%Y")
    end
    render layout: "admin"
  end

  def update
    @profile = User.find_by_id(params[:id]).profile
    if(@profile.update_attributes(params[:profile]))
      @profile.dob = DateTime.strptime(params["profile"]["dob"], "%d-%m-%Y")  unless params["profile"]["dob"].strip.empty?
      @profile.save
      flash[:notice] = "You have successfully updated your profile."
      redirect_to admin_employers_path
    else
      render :edit
      render layout: "admin"
    end
  end

  def destroy
    @employer = User.find_by_id params[:id]
    if @employer.destroy!
      redirect_to admin_employers_path()
    else
      flash[:error] = "Failed to delete project."
      redirect_to admin_employers_path()
    end
  end

  private
  def validate_user
    head :forbidden unless current_user.type.name == 'admin'
  end

end

app/controllers/employers_controller.rb
class EmployersController < ApplicationController
	before_filter :authenticate_user!, :except => [:show, :index]
  before_filter :validate_user, :except => [:show, :index]

  def index
    @user = current_user
  end

  def view_profile
    @user = current_user
    render :index
  end

  def edit
  	@profile = User.find_by_id(current_user.id).profile
  	unless @profile.dob
      @profile.dob = DateTime.now().strftime("%d-%m-%Y")
    else
      @profile.dob = @profile.dob.strftime("%d-%m-%Y")
    end
  end

  def show
    @profile = User.find_by_id(params[:id]).profile
    unless @profile.dob
      @profile.dob = DateTime.now()
    end
  end

  def update
  	@profile = User.find_by_id(current_user.id).profile
    params[:profile]["photo_path"] = save_photo("fileupload") if params[:fileupload]
    old_profile_photo = @profile.photo_path
  	if(@profile.update_attributes(params[:profile]))
      delete_photo([old_profile_photo]) if old_profile_photo
      @profile.dob = DateTime.strptime(params["profile"]["dob"], "%d-%m-%Y")  unless params["profile"]["dob"].strip.empty?
      @profile.save
      flash[:notice] = "You have successfully updated your profile."
      redirect_to employers_path
    else
      render :edit
    end
  end

  private

  def delete_photo photo_name
    UploadUtils.purgePhotos(photo_name)
  end  

  def save_photo file_param
    file = params[file_param] || {}
    file_name = DateTime.now().to_i.to_s + file.original_filename 
    file_data = File.read(file.tempfile)
    UploadUtils.uploadSingleFile file_name, file_data if file_data
    file_name
  end

  def validate_user
    head :forbidden unless current_user.type.name == 'employer'
  end

end

app/views/employers/_form_show.html.erb
<form class='form-horizontal' >   
  <fieldset>
    <legend class="text-left"><%= profile.user.display_name %></legend>
    <div class="form-group">
      <label class="col-md-3 control-label">First Name</label>
      <div class="col-md-9 top-seven">
        : <%= profile.first_name %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-md-3 control-label">Last Name</label>
      <div class="col-md-9 top-seven">
        : <%= profile.last_name %>
      </div>
    </div>    

    <div class="form-group">
      <label class="col-md-3 control-label">Sex</label>
      <div class="col-md-9 top-seven">
       : <%= profile.sex %>
      </div>
    </div>

    <% if current_user and current_user.type.name == "admin"%>
      <div class="form-group">
        <label class="col-md-3 control-label" for="name">Company</label>
        <div class="col-md-9 top-seven">
          : <%= profile.company || "" %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-md-3 control-label" >Date Of Birth</label>
        <div class="col-md-9 top-seven">
          : <%= profile.dob || "" %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-md-3 control-label" >Position</label>
        <div class="col-md-9 top-seven">
          : <%= profile.position %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-md-3 control-label">Phone Number</label>
        <div class="col-md-9 top-seven">
         : <%= profile.phone_number %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-md-3 control-label" >Address</label>
        <div class="col-md-9 top-seven">
          : <%= profile.address %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-md-3 control-label" >A Brief Bio</label>
        <div class="col-md-9 top-seven">
          : <%= profile.description %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-md-3 control-label" >Skill</label>
        <div class="col-md-9 top-seven">
          : <%= profile.skill %>
        </div>
      </div>

      <!-- Form actions -->
      <div class="form-group">
        <label class="col-md-3 control-label" ></label>
        <div class="col-md-9">
          
        </div>
      </div>
    <% end %>
  </fieldset>
</form>

app/views/employers/edit.html.erb
<div class="container">
  <div class="col-md-9 col-md-offset-1">
    <%= form_for(@profile, :url => {:action => "update"} , :html => {:class => 'form-horizontal', multipart: true} ) do |f| %>       
      <div class="row">
        <div class="col-lg-2">
          <div class="fileinput fileinput-new" data-provides="fileinput">
            <div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
              <img src="/profile/<%= @profile.photo_path %>" data-src="holder.js/100%x100%" alt="...">
            </div>
            <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"></div>
            <div>
              <span class="btn btn-default btn-file"><span class="fileinput-new">Select image</span><span class="fileinput-exists">Change</span><input name="fileupload" type="file" name="..."></span>
              <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
            </div>
          </div>
        </div>
        <div class="col-lg-10">  
          <fieldset>
            <div class="form-group">
              <label class="col-md-4 control-label" for="name">First Name</label>
              <div class="col-md-8">
                <%= f.text_field :first_name, :class =>"form-control", :required => "required", :placeholder => "Your first name" %>
              </div>
            </div>

            <div class="form-group">
              <label class="col-md-4 control-label" for="name">Last Name</label>
              <div class="col-md-8">
                <%= f.text_field :last_name, :class =>"form-control", :required => "required", :placeholder => "Your last name" %>
              </div>
            </div>

            <div class="form-group">
              <label class="col-md-4 control-label" for="name">Sex</label>
              <div class="col-md-8">
                <%= f.select(:sex, options_for_select(Profile::SEX.collect {|key,value| [key,value] }, f.object.sex), {},{ :class => 'form-control' }) %>
              </div>
            </div>

            <div class="form-group">
              <label class="col-md-4 control-label" for="name">Company</label>
              <div class="col-md-8">
                <%= f.text_field :company, :class =>"form-control", :required => "required", :placeholder => "Your company name" %>
              </div>
            </div>

            <div class="form-group">
              <label class="col-md-4 control-label" for="name">Skill</label>
              <div class="col-md-8">
                <%= f.select(:skill, options_for_select(Industry::INDUSTRY.collect {|key,value| [key,value] }, f.object.skill), {},{ :class => 'form-control', :onchange => 'queryPosition(this)' }) %>
              </div>
            </div>

            <div class="form-group">
              <label class="col-md-4 control-label" for="name">Date Of Birth</label>
              <div class="col-md-8">
                <%= f.text_field :dob, :class =>"form-control datepicker", :required => "required", :placeholder => "Your date of birth" %>
              </div>
            </div>

            <div class="form-group">
              <label class="col-md-4 control-label" for="name">Phone Number</label>
              <div class="col-md-8">
                <%= f.text_field :phone_number, :class =>"form-control", :required => "required", :placeholder => "Your primary phone number" %>
              </div>
            </div>

            <div class="form-group">
              <label class="col-md-4 control-label" for="name">Address</label>
              <div class="col-md-8">
                <%= f.text_area :address, :class =>"form-control", :required => "required", :placeholder => "Your current address" %>
              </div>
            </div>

            <div class="form-group">
              <label class="col-md-4 control-label" for="name">Additional information</label>
              <div class="col-md-8">
                <%= f.text_area :description, :class =>"form-control", :required => "required", :placeholder => "Please enter your profile description here..." %>
              </div>
            </div>    

            <!-- Form actions -->
            <div class="form-group">
              <label class="col-md-4"></label>
              <div class="col-md-8">
                <button class="btn btn-success">Update Profile</button>  <a href="<%= employers_path() %>" class="btn btn-danger">Cancel</a>
              </div>
            </div>
          </fieldset>
        </div>
      </div>
    <% end %>
  </div>
</div>

<script>
    $('.datepicker').datepicker({format: 'dd-mm-yyyy'})
</script>

app/views/employers/index.html.erb
<div class="container">
  <div class="pull-right right-menu" style="padding-right:15px;">
    <%= link_to " Post More Project", new_project_path(), :method => :get %> |
    <%= link_to " Support ", contact_us_path(), :method => :get %>
  </div>
  <div class="row">
    <div class="col-lg-3">
      <center>
        <img src="/profile/<%= @user.profile.photo_path %>" name="aboutme" width="200" height="150">
		  </center>
      <h3><%= @user.display_name %></h3>
      <label> <%= @user.profile.sex || "--" %> </label><br/>
      <label> Employer </label><br/>
      <label> Company : <%= @user.profile.company || "--"%> </label><br/>
      <label> Skill : <%= @user.profile.skill || "--"%> </label><br/>
      <a href="mailto:<%= current_user.email %>"><label><%= @user.email %></label></a><br/>
      <label> <%= @user.profile.phone_number || ""%> </label><br />
      <a type="button" class="btn btn-labeled btn-primary" href="<%= edit_employer_path(@user) %>">
        <span class="btn-label"><i class="glyphicon glyphicon-cog"></i></span>
        Edit
      </a>
    </div>
    <div class="col-lg-9">
      <h4> My Projects </h4>
      <div class="well">
        <table id="mytable" class="table table-bordred table-striped">
          <thead>
            <th>Project</th>
            <th>Freelancer</th>
            <th>Start date</th>
            <th>End date</th>
            <th>Budget</th>
            <th></th>
          </thead>
          <% if current_user.projects.size > 0 %>
            <% current_user.projects.each do |p| %>     
              <tbody>
                <tr>
                  <td><%= link_to p.name, project_path(p), :method => :get %></td>
                  <td><%= p.consultant_name %></td>
                  <td><%= p.start_date.to_date %></td>
                  <td><%= p.end_date.to_date %></td>
                  <td>$<%= p.budget %></td>
                  <td>
                    <%= link_to raw("<span class='glyphicon glyphicon-edit'></span> Edit"), edit_project_path(p), :method => :get, :class => 'btn btn-info btn-xs' %>
                    <%= link_to raw("<span class='glyphicon glyphicon-remove'></span> Del"), project_path(p), :method => :delete, :class => 'btn btn-danger btn-xs' %>
                  </td>
                </tr>
              </tbody>
            <% end %>
          <% else %>

          <% end %>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/employers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-1">
    </div>
    <div class="col-lg-6">
      <%= render "form_show", {:profile => @profile} %>
    </div>
    <div class="col-lg-4">
      <legend class="text-left">Project Post</legend>
        <% if @profile.user.projects.size > 0 %>
          <ul class="list-group">
            <% @profile.user.projects.each do |p| %>
              <%= link_to "#{p.name} - $#{p.budget}", project_path(p), :method => :get, :class => "list-group-item" %>
            <% end %>
          </ul>
        <% else %>
          Not yet post any project yet
        <% end %>
    </div>
  </div>
</div>