config/routes.rb
Rails.application.routes.draw do
  devise_for :users

    root 'pages#index'
    match 'welcome' => 'pages#welcome', :via => :get
    match 'contact_us' => 'pages#contactus', :via => :get
    match 'about_us' => 'pages#aboutus', :via => :get
    match 'how_it_work' => 'pages#howitwork', :via => :get
    match 'be_an_employer' => 'pages#beanemployer', :via => :get
    match 'be_a_freelancer' => 'pages#beafreelancer', :via => :get
    match 'register_employer' => 'users#register_employer', :via => :get
    match 'register_freelancer' => 'users#register_freelancer', :via => :get
    match 'save_employer' => 'users#save_employer', :via => :post
    match 'save_freelancer' => 'users#save_freelancer', :via => :post
    match 'get_position' => 'users#get_position', :via => :get
    match 'freelancer/:name' => 'freelancers#view_profile', :via => :get
    match 'employer/:name' => 'employers#view_profile', :via => :get

    resources :users do
      collection do
        post 'register'
      end

      member do
        put 'update_password'
        get 'change_password'

      end
    end

    resources :projects do
      member do
        post 'post_bid'
        get 'detail'
        put 'assign_consultant'
      end
    end
    resources :contact_us
    resources :freelancers
    resources :employers

    namespace :admin do
      resources :freelancers
      resources :employers
      resources :projects do
        member do
          put 'assign_consultant'
        end
      end
      resources :internal_users do
        collection do 
          get 'my_profile'
          put 'update_password'
          get 'change_password'
        end
      end
    end

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sabay Trade</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "jasny", "data-turbolinks-track" => true %>
    <%= stylesheet_link_tag    "jasny", media: "all", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
		<%= tinymce_assets %>

  </head>
  <body>
		<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
			<div class="container">
				<!-- Brand and toggle get grouped for better mobile display -->
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="#">Sabay Trade</a>
				</div>

				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav">
						<li class=<%= section_active("admin/projects")  %>><%= link_to raw("<span class='glyphicon glyphicon-file'></span> Projects"), admin_projects_path(), :method => :get %> </li>
						<li class=<%= section_active("admin/employers")  %>><%= link_to raw("<span class='glyphicon glyphicon-user'></span> Employers"), admin_employers_path(), :method => :get %></li>
						<li class=<%= section_active("admin/freelancers")  %>><%= link_to raw("<span class='glyphicon glyphicon-user'></span> Freelancers"), admin_freelancers_path(), :method => :get %></li>
						<li class=<%= section_active("admin/internal_users")  %>><%= link_to raw("<span class='glyphicon glyphicon-cog'></span> Settings"), admin_internal_users_path(), :method => :get %></li>
					</ul>

					<ul class="nav navbar-nav navbar-right">
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown"> <%= current_user.email %> <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><a href="<%= my_profile_admin_internal_users_path() %>">My Profile</a></li>
								<li><a href="<%= change_password_admin_internal_users_path() %>">Change Password</a></li>
								<li class="divider"></li>
								<li><%= link_to " Sign Out ", destroy_user_session_path(), :method => :delete %></li>
							</ul>
						</li>
					</ul>
				</div><!-- /.navbar-collapse -->
			</div><!-- /.container-fluid -->
		</nav>
		<br />
		<center>
			<% if flash[:error] -%>
				<button id="autoclosable-btn-danger" class="btn btn-primary btn-danger btn-block">
				  <%=h flash[:error] %>
				</button>
			<% end -%>
			<% if flash[:notice] -%>
				<button id="autoclosable-btn-info" class="btn btn-primary btn-info btn-block">
				  <%=h flash[:notice] %>
			  </button>
			<% end -%>
		</center>
		<%= yield %>
		<hr class="hrfooter" />
    <footer class="footer-page">
      <center>&copy; SabayTrade / ALL RIGHTS RESERVED 2015</center>
    </footer>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Sabay Trade</title>
	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= stylesheet_link_tag    "datepicker", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "bootstrap-datepicker", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "jasny", "data-turbolinks-track" => true %>
    <%= stylesheet_link_tag    "jasny", media: "all", "data-turbolinks-track" => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
    <div class="navbar">
      <div class="navbar-inner sabay-header">
        <div class="hearder_narrow">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </a>
          <a class="brand" href="/" name="top">
            <img src="/logo.png" alt="..." class="img-rounded">
          </a>
          <% unless current_user %>
            <div class="pull-right right-menu" style="padding-right:10px;">
              <%= link_to " ABOUT US", about_us_path(), :method => :get, :style => 'color:grey;padding-right:5px;' %> 
              <%= link_to " CONTACT US", contact_us_path(), :method => :get, :style => 'color:grey;padding-right:5px;' %> 
              <a href="<%= new_user_session_path() %>" class="btn btn-danger">Sign In</a>
            </div>
          <% else %>
            <div class="pull-right right-menu" style="padding-right:10px;">
              Welcome <%= link_to current_user.display_name, "#", :method => :get, :style => 'color:white;padding-right:5px;' %>
              <%= link_to " Sign Out ", destroy_user_session_path(), :method => :delete, :class => "btn btn-danger" %>
            </div>
          <% end %>
        <!--/.nav-collapse -->
        </div>
      <!--/.container-fluid -->
      </div>
    <!--/.navbar-inner -->
    </div>
    <%= yield %>
    <div style="clear:both;"></div>
    <hr class="hrfooter" />
    <footer class="footer-page">
      <center>&copy; SabayTrade / ALL RIGHTS RESERVED 2015</center>
    </footer>
	</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sabay Trade</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="navbar">
      <div class="navbar-inner sabay-header">
        <div class="hearder_narrow">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </a>
          <a class="brand" href="/" name="top">
            <img src="/logo.png" alt="..." class="img-rounded">
          </a>
        <!--/.nav-collapse -->
        </div>
      <!--/.container-fluid -->
      </div>
    <!--/.navbar-inner -->
    </div>
    <%= yield %>
    <hr class="hrfooter" />
    <footer class="footer-page">
      <center>&copy; SabayTrade / ALL RIGHTS RESERVED 2015</center>
    </footer>
  </body>
</html>